version: "3"

tasks:
  build:
    internal: true
    cmds:
      - docker build --build-arg BASE_IMAGE={{.BASE_IMAGE}} -t nvim-full:{{.TAG}} .
    requires:
      vars: [BASE_IMAGE, TAG]

  stable:
    cmds:
      - task: build
        vars:
          BASE_IMAGE: nvim-base:stable
          TAG: stable

  latest:
    cmds:
      - task: build
        vars:
          BASE_IMAGE: nvim-base:latest
          TAG: latest
