---
version: "3"

tasks:
  build:
    internal: true
    cmds:
      - docker build --build-arg BRANCH={{.BRANCH}} -t nvim-base:{{.TAG}} .
    requires:
      vars: [BRANCH, TAG]

  stable:
    cmds:
      - task: build
        vars:
          BRANCH: release-0.10
          TAG: release-0.10

  latest:
    cmds:
      - task: build
        vars:
          BRANCH: master
          TAG: latest
