name: base-stable

on:
  push:
    branches:
      - "main"
    paths:
      - "./base/Dockerfile"
  workflow_run:
    workflows: [hadolint]
    types: [completed]

jobs:
  base-stable:
    runs-on: ubuntu-latest
    # Only run when hadolint succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./base/Dockerfile
          build-args: BRANCH=stable
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvim-base:stable
