name: full-stable

on:
  push:
    branches:
      - "main"
  workflow_run:
    workflows: [base-stable]
    types: [completed]

jobs:
  base-stable:
    runs-on: ubuntu-latest
    # Only run when base-stable succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./base/Dockerfile
          build-args: BASE_IMAGE=nvim-base:stable
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvim-full:stable
