name: hadolint

on:
  push:
    branches:
      - "main"
    paths:
      - "**/Dockerfile"

jobs:
  hadolint:
    runs-on: ubuntu-22.04
    name: Hadolint
    steps:
      - uses: actions/checkout@v3
      - uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "**/Dockerfile"
